export default {
  TanzeemUlMadaris: "Tanzeem ul Madaris",
  selectionOfGender: "Selection of gender",
  selectionOfSession: "Selection of session",
  male: "Male",
  female: "Female",
  gender: "Gender",
  session: "Session",
  final: "Final",
  secondFinal: "Second Final",
  temporal: "Temporal",
  year: "Year",
  selectionOfRank: "Selection of rank",
  tajweedAlQuran: `Tajweed Al-Qur'an`,
  publicFirst: "Public First",
  publicSecond: "Public Second",
  feature_1: "Feature 1",
  feature_2: "Feature 2",
  aliya_1: "Aliya 1",
  aliya_II: "Aliya II",
  world_I: "World I",
  world_II: "World II",
  medium: "Medium",
  takhsal_Per_Fiqh_I: "Takhsal Per Fiqh I",
  takhsal_Per_Fiqh_II: "Takhsal Per Fiqh II",
  specializationEntranceTest: "Specialization Entrance Test",
  rollNo: "Roll no",
  enterYourRollNo: "Enter your roll no",
  showResult: "See the result",
  AnnualExamination2024: "Annual Examination 2024",
  rank: "Rank",
  rankAlShahadatulTanwiyyahGeneralYear1:
    "Rank: Al-Shahadat-ul-Tanwiyyah General Year 1 (Matriculation)",
  studentName: "Student name",
  fatherName: "Father name",
  dateOfBirth: "Date of birth",
  nameOfInstitution: "Name of institution",
  registrationNo: "Registration no",
  number: "No",
  subjects: "Subjects",
  totalMarks: "Total marks",
  obtainedMarks: "Obtained marks",
  status: "Status",
  note: "Note",
  noteDesc:
    "This is the electronic version of the result card, in case of any inaccuracies/errors contact the examination department immediately.",
  websitePrintResult: "Website Print Result",
  controllerExams: "Controller Exams",
  downloadResult: "Download Result",
  result: "Result",
  total: "Total",
  registrationNoPlaceholder: "Please enter your registration number",
  formText:
    'Enter valid registration and roll number to check the result. And click on the "Result" button at the bottom',
  fillFieldsAlert: "Please fill out all fields.",
  OK: "OK",
  language: "Language",
  nazamUlMadaris: "Nazm al-Madaris",
  contact: "Contact",
  provincialOffices: "Provincial offices",
  downloads: "Downloads",
  results: "Results",
  background: "Background",
  AimsAndObjectives: "Aims and Objectives",
  signInForm: "Sign In Form",
  User: "User",
  Password: "Password",
  UserName: "Username",
  SignIn: "Sign In",
  Admin: "Admin",
  incorrectCredentials: "The user name and password are incorrect",
  loginSuccessMsg: 'Success", "You have successfully logged in!',
  ViewAdministrativeLoginAccounts: "View administrative login accounts",
  SeeAffiliatedSchools: "See affiliated schools",
  UploadOrChangePhotos: "Upload or change photos",
  UploadOrChangeNews: "Upload or change news",
  SeeMadrasasMessages: "See Madrasas messages",
  SeeScholarsLoginAccounts: "See Scholars Login Accounts",
  ScholarsRecords: "Scholars Records",
  SeeTheOfficialEmail: "See the official email",
  welcomeText: "Assalam o Alaikum",
  welcomeNote: "Welcome to the administration page of the Tanzeem-Al-Madaris",
  accounts: "Accounts",
  affiliatedSchools: "Affiliated Schools",
  madrasasMessages: "Madrasas Messages",
  emails: "Emails",
  scholarLoginAccounts: "Scholars Login Accounts",
  createNewUser: "Create New User",
  createUser: "Create User",
  serialNo: "S.No",
  actions: "Actions",
  district: "District",
  nameOfInstitutionAddress: "Name of Institution/Address",
  nameOfInstitutionAndAddress: "Name of Institution and Address",
  accessionNo: "Accession No",
  getRecord: "Get Record",
  madrisaCode: "Madrisa Code",
  madrisaDarja: "Madrisa Darja",
  dateOfAccession: "Date of Accession",
  yearOfEstablishment: "Year of Establishment",
  affiliationStatus: "Affiliation Status",
  honorableGovernor: "Honorable Governor",
  phoneNo: "Phone No",
  moreInfo: "More Info",
  uploadImages: "Upload Images",
  pictureCategory: "Picture Category",
  selectImagePath: "Select Image Path",
  pictureCaption: "Picture Caption",
  enterCaption: "Enter Caption",
  uploadImage: "Upload Image",
  addNewCategory: "Add New Category",
  editSelectedCategory: "Edit Selected Category",
  selectCategory: "Select Category",
  newCategory: "New Category",
  newName: "New Name",
  add: "Add",
  edit: "Edit",
  categoryName: "Category Name",
  picture: "Picture",
  uploadNews: "Upload News",
  newsOnAlert: "News On Alert",
  newsHeading: "News Heading",
  newsDetails: "News Details",
  chooseImage: "Choose Image",
  writeAboutNewsAlert: "Write About News Alert...",
  enterNewHeading: "Enter New Heading",
  writeNewsDetails: "Write News Details",
  newsHeadingDetail: "News Heading/Detail",
  published: "Published",
  current: "Current",
  newsHot: "News Hot",
  newsOrder: "News Order",
  messageDescription: "Message Description",
  emailAddresses: "Email Addresses",
  cnic: "CNIC No",
  mobileNo: "Mobile No",
  pastExperience: "Past Experience",
  requiredDuties: "Required Duties",
  permanentAddress: "Permanent Address",
  currentAddress: "Current Address",
  dateOfEnrollment: "Date Of Enrollment",
  date: "Date",
  name: "Name",
};
