export default {
  selectionOfGender: "Selection of gender",
  selectionOfSession: "Selection of session",
  male: "Male",
  female: "Female",
  gender: "Gender",
  session: "Session",
  final: "Final",
  secondFinal: "Second Final",
  temporal: "Temporal",
  year: "Year",
  selectionOfRank: "Selection of rank",
  tajweedAlQuran: `Tajweed Al-Qur'an`,
  publicFirst: "Public First",
  publicSecond: "Public Second",
  feature_1: "Feature 1",
  feature_2: "Feature 2",
  aliya_1: "Aliya 1",
  aliya_II: "Aliya II",
  world_I: "World I",
  world_II: "World II",
  medium: "Medium",
  takhsal_Per_Fiqh_I: "Takhsal Per Fiqh I",
  takhsal_Per_Fiqh_II: "Takhsal Per Fiqh II",
  specializationEntranceTest: "Specialization Entrance Test",
  rollNo: "Roll no",
  enterYourRollNo: "Enter your roll no",
  showResult: "See the result",
  AnnualExamination2024: "Annual Examination 2024",
  rank: "Rank",
  rankAlShahadatulTanwiyyahGeneralYear1:
    "Rank: Al-Shahadat-ul-Tanwiyyah General Year 1 (Matriculation)",
  studentName: "Student name",
  fatherName: "Father name",
  dateOfBirth: "Date of birth",
  nameOfInstitution: "Name of institution",
  registrationNo: "Registration no",
  number: "No",
  subjects: "Subjects",
  totalMarks: "Total marks",
  obtainedMarks: "Obtained marks",
  status: "Status",
  note: "Note",
  noteDesc:
    "This is the electronic version of the result card, in case of any inaccuracies/errors contact the examination department immediately.",
  websitePrintResult: "Website Print Result",
  controllerExams: "Controller Exams",
  downloadResult: "Download Result",
  result: "Result",
  total: "Total",
  registrationNoPlaceholder: "Please enter your registration number",
  formText:
    'Enter valid registration and roll number to check the result. And click on the "Result" button at the bottom',
  fillFieldsAlert: "Please fill out all fields.",
  OK: "OK",
};
