export default {
  selectionOfGender: "جنس کا انتخاب",
  selectionOfSession: "سیشن کا انتخاب",
  male: "مرد",
  female: "عورت",
  gender: "جنس",
  session: "سیشن",
  final: "سالانا",
  secondFinal: "دوسرا سالانا",
  temporal: "ضمنی",
  year: "سال",
  selectionOfRank: "عہدے کا انتخاب",
  tajweedAlQuran: `تجویدالقران`,
  publicFirst: "عامہ اول",
  publicSecond: "عامہ دوئم",
  feature_1: "خاصہ اول",
  feature_2: "خاصہ دوئم",
  aliya_1: "عالیہ اول",
  aliya_II: "عالیہ دوئم",
  world_I: "عالمیہ اول",
  world_II: "عالمیہ دوئم",
  medium: "متوسطہ",
  takhsal_Per_Fiqh_I: "تخصص فی الفقہ اول",
  takhsal_Per_Fiqh_II: "تخصص فی الفقہ دوم",
  specializationEntranceTest: "تخصص داخلہ ٹیسٹ",
  rollNo: "رول نمبر",
  enterYourRollNo: "اپنا رول نمبر درج کریں۔",
  showResult: "نتیجہ دیکھیں",
  AnnualExamination2024: "سالانہ امتحان 2024",
  rank: "درجہ",
  rankAlShahadatulTanwiyyahGeneralYear1:
    "درجہ: الشہداء التنویہ عمومی سال 1 (میٹرک)",
  studentName: "طالب علم کا نام",
  fatherName: "والد کا نام",
  dateOfBirth: "تاریخ پیدائش",
  nameOfInstitution: "ادارے کا نام",
  registrationNo: "رجسٹریشن نمبر",
  number: "نمبر شمار",
  subjects: "مضامین",
  totalMarks: "کل نمبر",
  obtainedMarks: "حاصل کردہ نمبر",
  status: "کیفیت",
  note: "نوٹ",
  noteDesc:
    " یہ نتیجہ کارڈ کا الیکٹرانک ورژن ہے ، کسی سہو/غلطی کی صورت میں فوری طور پر شعبہ امتحانات سے رابطہ کریں۔",
  websitePrintResult: "ویب سا ئٹ نتیجہ پرنٹ",
  controllerExams: "کنٹرولر امتحانات",
  downloadResult: "نتیجہ ڈاؤن لوڈ کریں۔",
  result: "نتیجہ",
  total: "میزان",
  registrationNoPlaceholder: "براہ کرم اپنا رجسٹریشن نمبر درج کریں۔",
  formText:
    'نتیجہ دیکھنے کے لیے درست رجسٹریشن و رول نمبر درج کریں۔ اور نچلی جانب "نتیجہ" والے بٹن پہ کلک کریں',
  fillFieldsAlert: "براہ کرم تمام فیلڈز کو پُر کریں۔",
  OK: "ٹھیک ہے",
};
