export default {
  TanzeemUlMadaris: "تنظیم المدارس",
  selectionOfGender: "جنس کا انتخاب",
  selectionOfSession: "سیشن کا انتخاب",
  male: "مرد",
  female: "عورت",
  gender: "جنس",
  session: "سیشن",
  final: "سالانا",
  secondFinal: "دوسرا سالانا",
  temporal: "ضمنی",
  year: "سال",
  selectionOfRank: "عہدے کا انتخاب",
  tajweedAlQuran: `تجویدالقران`,
  publicFirst: "عامہ اول",
  publicSecond: "عامہ دوئم",
  feature_1: "خاصہ اول",
  feature_2: "خاصہ دوئم",
  aliya_1: "عالیہ اول",
  aliya_II: "عالیہ دوئم",
  world_I: "عالمیہ اول",
  world_II: "عالمیہ دوئم",
  medium: "متوسطہ",
  takhsal_Per_Fiqh_I: "تخصص فی الفقہ اول",
  takhsal_Per_Fiqh_II: "تخصص فی الفقہ دوم",
  specializationEntranceTest: "تخصص داخلہ ٹیسٹ",
  rollNo: "رول نمبر",
  enterYourRollNo: "اپنا رول نمبر درج کریں۔",
  showResult: "نتیجہ دیکھیں",
  AnnualExamination2024: "سالانہ امتحان 2024",
  rank: "درجہ",
  rankAlShahadatulTanwiyyahGeneralYear1:
    "درجہ: الشہداء التنویہ عمومی سال 1 (میٹرک)",
  studentName: "طالب علم کا نام",
  fatherName: "والد کا نام",
  dateOfBirth: "تاریخ پیدائش",
  nameOfInstitution: "ادارے کا نام",
  registrationNo: "رجسٹریشن نمبر",
  number: "نمبر شمار",
  subjects: "مضامین",
  totalMarks: "کل نمبر",
  obtainedMarks: "حاصل کردہ نمبر",
  status: "کیفیت",
  note: "نوٹ",
  noteDesc:
    " یہ نتیجہ کارڈ کا الیکٹرانک ورژن ہے ، کسی سہو/غلطی کی صورت میں فوری طور پر شعبہ امتحانات سے رابطہ کریں۔",
  websitePrintResult: "ویب سا ئٹ نتیجہ پرنٹ",
  controllerExams: "کنٹرولر امتحانات",
  downloadResult: "نتیجہ ڈاؤن لوڈ کریں۔",
  result: "نتیجہ",
  total: "میزان",
  registrationNoPlaceholder: "براہ کرم اپنا رجسٹریشن نمبر درج کریں۔",
  formText:
    'نتیجہ دیکھنے کے لیے درست رجسٹریشن و رول نمبر درج کریں۔ اور نچلی جانب "نتیجہ" والے بٹن پہ کلک کریں',
  fillFieldsAlert: "براہ کرم تمام فیلڈز کو پُر کریں۔",
  OK: "ٹھیک ہے",
  language: "زبان",
  nazamUlMadaris: "نظم المدارس",
  contact: "رابطہ",
  provincialOffices: "صوبائی دفاتر",
  downloads: "ڈاؤن لوڈز",
  results: "نتائج",
  background: "پس منظر",
  AimsAndObjectives: "اغراض ومقاصد",
  signInForm: "سائن ان فارم",
  User: "یوزر",
  Password: "پاسورڈ",
  UserName: "یوزر کا نام",
  SignIn: "سائن ان",
  Admin: "ایڈمن",
  incorrectCredentials: "یوزر کا نام اور پاس ورڈ غلط ہے۔",
  loginSuccessMsg: 'کامیابی"، "آپ کامیابی سے لاگ ان ہو گئے ہیں!',
  ViewAdministrativeLoginAccounts: "انتظامی لاگ ان اکاؤنٹس دیکھیں",
  SeeAffiliatedSchools: "ملحقہ مدارس دیکھیں",
  UploadOrChangePhotos: "تصاویر اپ لوڈ یا تبدیل کریں",
  UploadOrChangeNews: "نیوز اپ لوڈ یا تبدیل کریں",
  SeeMadrasasMessages: "مدارس کے پیغامات دیکھیں",
  SeeScholarsLoginAccounts: "علمائے کرام لاگ ان اکاؤنٹس دیکھیں",
  ScholarsRecords: "علمائے کرام ریکارڈز",
  SeeTheOfficialEmail: "آفیشل ای میل دیکھیں",
  welcomeText: "السلام علیکم ورحمۃ اللہ",
  welcomeNote: "تنظیم المدارس ویب سائٹ کے انتظامی صفحہ پر خوش آمدید ",
  accounts: "اکاؤنٹس",
  affiliatedSchools: "ملحقہ مدارس",
  madrasasMessages: "مدارس کے پیغامات",
  emails: "ای میلز",
  scholarLoginAccounts: "علمائے کرام لاگ ان اکاؤنٹس",
  createNewUser: "نیا صارف بنائیں",
  createUser: "صارف بنائیں",
  serialNo: "سیریل نمبر",
  actions: "اعمال",
  district: "ضلع",
  nameOfInstitutionAddress: "ادارے کا نام/ پتہ",
  nameOfInstitutionAndAddress: "نام ادارہ و پتہ",
  accessionNo: "الحاق نمبر",
  getRecord: "ریکارڈ حاصل کریں",
  madrisaCode: "مدرسہ کوڈ",
  madrisaDarja: "مدرسہ دارجہ",
  dateOfAccession: "تاریخ الحاق",
  yearOfEstablishment: "سنہ تاسیس",
  affiliationStatus: "درجہ الحاق",
  honorableGovernor: "مہتمم ؍ناظم اعلیٰ",
  phoneNo: "فون نمبر",
  moreInfo: "دیگر معلومات",
  uploadImages: "تصاویر اپ لوڈ کریں",
  pictureCategory: "تصویر کا زمرہ",
  selectImagePath: "تصویری راستہ منتخب کریں",
  pictureCaption: "تصویری کیپشن",
  enterCaption: "کیپشن درج کریں",
  uploadImage: "تصویراپ لوڈ کریں",
  addNewCategory: "نیا زمرہ شامل کریں",
  editSelectedCategory: "منتخب کردہ زمرہ میں ترمیم کریں",
  selectCategory: "زمرہ منتخب کریں",
  newCategory: "نیا زمرہ",
  newName: "نیا نام",
  add: "شامل کریں",
  edit: "ترمیم",
  categoryName: "قسم کا نام",
  picture: "تصویر",
  uploadNews: "خبریں اپ لوڈ کریں",
  newsOnAlert: "نیوز الرٹ",
  newsHeading: "نیوز ہیڈ لائنز",
  newsDetails: "خبروں کی تفصیلات",
  chooseImage: "تصویر کا انتخاب کریں",
  writeAboutNewsAlert: "نیوز الرٹ کے بارے میں لکھیں...",
  enterNewHeading: "نئی سرخی داخل کریں",
  writeNewsDetails: "خبروں کی تفصیلات لکھیں",
  newsHeadingDetail: "خبر کی سرخی/تفصیل",
  published: "شائع شدہ",
  current: "کرنٹ",
  newsHot: "خبریں گرم",
  newsOrder: "نیوز آرڈر",
  messageDescription: "پیغام کی تفصیل",
  emailAddresses: "ای میل ایڈریسز",
  cnic: "شناختی کارڈ نمبر",
  mobileNo: "موبائل نمبر",
  pastExperience: "گذشتہ تجربہ",
  requiredDuties: "مطلوبہ ڈیوٹی",
  permanentAddress: "مستقل پتہ",
  currentAddress: "موجودہ پتہ",
  dateOfEnrollment: "تاریخ اندراج",
  date: "تاریخ",
  name: "نام",
};
